baseurl = "http://www.ninjaducks.in/"
languageCode = "en-us"
title = "ninjaduck"
theme = "hugo-crisp"
pygmentsStyle = "colorful"
canonifyurls = true
[permalinks]
	top = "/:filename/"
[params]
	ga = "UA-47255777-1"
	disqus = "shivanshuag"
