baseurl = "http://ninjaducks.in/"
languageCode = "en-us"
title = "ninjaduck"
theme = "hugo-crisp"
pygmentsStyle = "colorful"

[permalinks]
	top = "/:filename/"
	hacking = "/hacking/:filename/"
	shorts = "shorts/:filename"

[params]
	ga = "UA-47255777-1"
	disqus = "shivanshuag"